import './globals.css';
import type { Metadata } from 'next';
import { Inter, Noto_Sans_KR } from 'next/font/google';
import { Footer, Header, Sidebar } from './_components';
import styles from './page.module.css';
import classNames from 'classnames';
const noto_Sans_KR = Noto_Sans_KR({
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  console.log('Hello');
  return (
    <html lang="en">
      <body className={classNames(noto_Sans_KR.className, styles.main)}>
        <Header className={styles.header} />
        <Sidebar className={styles.sidebar} />
        <div className={styles.body}>{children}</div>
        <Footer className={styles.footer} />
      </body>
    </html>
  );
}
